agent:
  # Agent name
  name: ${SCUTI_AGENT_NAME:-scuti}

  # Env mode (dev or prod)
  mode: ${SCUTI_AGENT_MODE:-dev}

  # Address
  address: ${SCUTI_AGENT_ADDRESS:-http://127.0.0.1:8000}

  # Global timeout
  timeout: ${SCUTI_AGENT_TIMEOUT:-50}

  # Agent labels
  labels: dc=ams-01,team=scuti,service=payment01

  # To expose on which port
  port: ${SCUTI_AGENT_PORT:-8000}

  # TLS configs
  tls:
    status: ${SCUTI_AGENT_TLS_STATUS:-off}
    crt_path: ${SCUTI_AGENT_TLS_PEMPATH:-cert/server.crt}
    key_path: ${SCUTI_AGENT_TLS_KEYPATH:-cert/server.key}

  # Remote management server configs
  management:
    # Remote server endpoint
    address: ${SCUTI_AGENT_MANAGEMENT_ADDRESS:-http://localhost:4000}
    # Host Group UUID
    host_group_uuid: ${SCUTI_AGENT_HG_UUID:-TBA}
    # Host UUID
    host_uuid: ${SCUTI_AGENT_H_UUID:-TBA}
    # Host Group Secret
    host_group_secret: ${SCUTI_AGENT_HG_SECRET:-TBA}
    # Host Secret
    host_secret: ${SCUTI_AGENT_H_SECRET:-TBA}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${SCUTI_AGENT_LOG_LEVEL:-debug}
    # Output can be stdout or abs path to log file /var/logs/scuti.log
    output: ${SCUTI_AGENT_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${SCUTI_AGENT_LOG_FORMAT:-json}
