version: '3.8'

services:
 app:
    build:
      context: .
    environment:
      PGUSER: root
      PGPASSWORD: D1q9f0C2&PEW
      PGDATABASE: scuti
      PGPORT: 5432
      PGHOST: db
    restart: unless-stopped
    ports:
      - '4000:4000'
    depends_on:
      - db
 db:
    image: postgres:15.6
    environment:
      POSTGRES_DB: scuti
      POSTGRES_USER: root
      POSTGRES_PASSWORD: D1q9f0C2&PEW
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  app:
    driver: local
