name: Agent CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.19", "1.20.4", "1.21.3"]
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make -f makefile.agent install_revive

      - name: Run make ci
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make -f makefile.agent ci
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make -f makefile.agent verify
